### ISSUE TITLE
Return tests in the same order

### ISSUE THREAD

**Issue by imcodingideas** [gSchool/map-filter-reduce-exercises#1]
We are encouraged to do the exercises in this order: .map(), .filter(), and .reduce() but the tests call for filter first. 

Could I rename the folders to have 1, 2, 3 in the file name to make it easy? Would you take that pull request?

**Comment by w3cj** [comment]
You can run tests in a single folder at a time:

`npm test ./map`

`npm test ./filter`

`npm test ./reduce`
